services:
  webapi:
    image: instructionrag
    container_name: webapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:8080"
       
  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"